// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type DeleteUserReq struct {
	Id int64 `json:"id"`
}

type DeleteUserResp struct {
	Status bool `json:"status"`
}

type HealthReq struct {
	Ping string `json:"ping"`
}

type HealthResp struct {
	Pong string `json:"pong"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Name     string `json:"name"`
	Gender   string `json:"gender,optional"`
}

type RegisterResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type UpdateUserReq struct {
	Id       int64  `json:"id"`
	Name     string `json:"name,optional"`
	Mobile   string `json:"mobile,optional"`
	Password string `json:"password,optional"`
	Gender   string `json:"gender,optional"`
}

type UpdateUserResp struct {
	Status bool `json:"status"`
}

type User struct {
	Id     int64  `json:"id"`
	Mobile string `json:"mobile"`
	Name   string `json:"name"`
	Gender string `json:"gender"`
}

type UserInfoReq struct {
	Id int64 `json:"id"`
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}
